/* tslint:disable */
/* eslint-disable */
/**
 * Mezura v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

import { AxiosInstance } from "axios";
import * as models from "./api";
import * as config from "./configuration"

class API {
    public static Configuration: config.Configuration;
    public static BaseUrl: string;
    public static AxiosInstance: AxiosInstance;
    static AccountApi: models.AccountApi;
    static ProductApi: models.ProductApi;
    static FreightBillApi: models.FreightBillApi;
    static AuthApi: models.AuthApi;

    public static initialize(baseUrl: string, axiosInstance: AxiosInstance) {
        this.BaseUrl = baseUrl;
        this.AxiosInstance = axiosInstance;
        this.Configuration = new config.Configuration({ basePath: baseUrl });
        this.AuthApi = new models.AuthApi(this.Configuration, baseUrl, axiosInstance);
        this.AccountApi = new models.AccountApi(this.Configuration, baseUrl, axiosInstance);
        this.ProductApi = new models.ProductApi(this.Configuration, baseUrl, axiosInstance);
        this.FreightBillApi = new models.FreightBillApi(this.Configuration, baseUrl, axiosInstance);
    }
}

export default API;